import { json, optionsResponse } from "../_shared/dashboard.ts";

const COUNTRIES = [
  {
    rank: 1,
    name: "North Korea",
    country: "North Korea",
    url: "https://www.opendoors.org/en-US/persecution/countries/north-korea/",
    flagImage: "https://flagcdn.com/w320/kp.png",
    christianPopulation: "400,000",
    population: "26,100,000",
    mainReligion: "Juche / Atheism",
    government: "Dictatorship",
    leader: "Kim Jong Un",
    prayerPoints: [
      "Pray for secret believers to be protected from discovery and punishment.",
      "Pray for Scripture, teaching, and Christian fellowship to reach isolated Christians.",
      "Pray that imprisoned and suffering believers would know Christ's nearness and endurance.",
    ],
  },
  {
    rank: 2,
    name: "Somalia",
    country: "Somalia",
    url: "https://www.opendoors.org/en-US/persecution/countries/somalia/",
    flagImage: "https://flagcdn.com/w320/so.png",
    christianPopulation: "Hundreds",
    population: "18,100,000",
    mainReligion: "Islam",
    government: "Federal parliamentary republic",
    leader: "Hassan Sheikh Mohamud",
    prayerPoints: [
      "Pray for Somali believers who must often worship and grow in secret.",
      "Pray for protection from extremist violence and family pressure.",
      "Pray that displaced Somalis would encounter faithful Christian witness and lasting peace.",
    ],
  },
  {
    rank: 3,
    name: "Yemen",
    country: "Yemen",
    url: "https://www.opendoors.org/en-US/persecution/countries/yemen/",
    flagImage: "https://flagcdn.com/w640/ye.png",
    christianPopulation: "A few thousand",
    population: "34,400,000",
    mainReligion: "Islam",
    government: "Provisional republic",
    leader: "Rashad al-Alimi",
    prayerPoints: [
      "Pray for believers isolated by conflict, poverty, and family pressure.",
      "Pray for secret fellowships to receive Scripture and pastoral care.",
      "Pray for peace and for faithful witness through humanitarian need.",
    ],
  },
  {
    rank: 4,
    name: "Libya",
    country: "Libya",
    url: "https://www.opendoors.org/en-US/persecution/countries/libya/",
    flagImage: "https://flagcdn.com/w640/ly.png",
    christianPopulation: "A few thousand",
    population: "7,100,000",
    mainReligion: "Islam",
    government: "Divided transitional government",
    leader: "Abdul Hamid Dbeibeh",
    prayerPoints: [
      "Pray for migrant believers facing danger and exploitation.",
      "Pray for Libyan Christians to find courage and discreet fellowship.",
      "Pray for stability, justice, and doors for gospel witness.",
    ],
  },
  {
    rank: 5,
    name: "Sudan",
    country: "Sudan",
    url: "https://www.opendoors.org/en-US/persecution/countries/sudan/",
    flagImage: "https://flagcdn.com/w640/sd.png",
    christianPopulation: "2,000,000",
    population: "49,300,000",
    mainReligion: "Islam",
    government: "Military-led transitional authority",
    leader: "Abdel Fattah al-Burhan",
    prayerPoints: [
      "Pray for churches serving amid war, displacement, and hunger.",
      "Pray for believers who have lost homes, leaders, and places of worship.",
      "Pray for peace and protection for vulnerable Christian communities.",
    ],
  },
  {
    rank: 6,
    name: "Eritrea",
    country: "Eritrea",
    url: "https://www.opendoors.org/en-US/persecution/countries/eritrea/",
    flagImage: "https://flagcdn.com/w640/er.png",
    christianPopulation: "2,700,000",
    population: "3,700,000",
    mainReligion: "Christianity / Islam",
    government: "One-party presidential republic",
    leader: "Isaias Afwerki",
    prayerPoints: [
      "Pray for believers imprisoned for their faith.",
      "Pray for families separated by detention and military pressure.",
      "Pray for endurance among underground churches.",
    ],
  },
  {
    rank: 7,
    name: "Nigeria",
    country: "Nigeria",
    url: "https://www.opendoors.org/en-US/persecution/countries/nigeria/",
    flagImage: "https://flagcdn.com/w640/ng.png",
    christianPopulation: "100,000,000",
    population: "223,800,000",
    mainReligion: "Christianity / Islam",
    government: "Federal presidential republic",
    leader: "Bola Tinubu",
    prayerPoints: [
      "Pray for believers facing militant violence and displacement.",
      "Pray for pastors and churches serving traumatized communities.",
      "Pray for justice, peace, and courageous witness.",
    ],
  },
  {
    rank: 8,
    name: "Pakistan",
    country: "Pakistan",
    url: "https://www.opendoors.org/en-US/persecution/countries/pakistan/",
    flagImage: "https://flagcdn.com/w640/pk.png",
    christianPopulation: "4,200,000",
    population: "241,500,000",
    mainReligion: "Islam",
    government: "Federal parliamentary republic",
    leader: "Shehbaz Sharif",
    prayerPoints: [
      "Pray for Christians vulnerable to blasphemy accusations and mob pressure.",
      "Pray for Christian families facing discrimination in work and education.",
      "Pray for churches to serve with wisdom and unity.",
    ],
  },
  {
    rank: 9,
    name: "Iran",
    country: "Iran",
    url: "https://www.opendoors.org/en-US/persecution/countries/iran/",
    flagImage: "https://flagcdn.com/w320/ir.png",
    christianPopulation: "800,000",
    population: "90,411,000",
    mainReligion: "Shia Islam",
    government: "Theocratic Republic",
    leader: "Supreme Leader Ayatollah Ali Khamenei",
    prayerPoints: [
      "Pray for imprisoned church leaders and believers under interrogation.",
      "Pray for house churches to grow in wisdom, unity, and courage.",
      "Pray that Persian Scripture and discipleship resources would continue to reach seekers.",
    ],
  },
  {
    rank: 10,
    name: "Afghanistan",
    country: "Afghanistan",
    url: "https://www.opendoors.org/en-US/persecution/countries/afghanistan/",
    flagImage: "https://flagcdn.com/w640/af.png",
    christianPopulation: "Thousands",
    population: "42,200,000",
    mainReligion: "Islam",
    government: "Islamic emirate",
    leader: "Hibatullah Akhundzada",
    prayerPoints: [
      "Pray for secret Afghan believers to be protected and strengthened.",
      "Pray for refugees and displaced families to encounter Christ's care.",
      "Pray for Scripture and discipleship to reach isolated seekers.",
    ],
  },
  {
    rank: 11,
    name: "India",
    country: "India",
    url: "https://www.opendoors.org/en-US/persecution/countries/india/",
    flagImage: "https://flagcdn.com/w640/in.png",
    christianPopulation: "71,000,000",
    population: "1,428,600,000",
    mainReligion: "Hinduism",
    government: "Federal parliamentary republic",
    leader: "Narendra Modi",
    prayerPoints: [
      "Pray for Christians facing local pressure, false accusations, and violence.",
      "Pray for pastors serving rural and marginalized communities.",
      "Pray for churches to respond with patience, courage, and love.",
    ],
  },
  {
    rank: 12,
    name: "Syria",
    country: "Syria",
    url: "https://www.opendoors.org/en-US/persecution/countries/syria/",
    flagImage: "https://flagcdn.com/w640/sy.png",
    christianPopulation: "579,000",
    population: "23,200,000",
    mainReligion: "Islam",
    government: "Authoritarian republic",
    leader: "Ahmed al-Sharaa",
    prayerPoints: [
      "Pray for churches serving amid trauma, poverty, and rebuilding.",
      "Pray for displaced believers and families considering whether to return.",
      "Pray for peace and renewed gospel witness.",
    ],
  },
  {
    rank: 13,
    name: "Saudi Arabia",
    country: "Saudi Arabia",
    url: "https://www.opendoors.org/en-US/persecution/countries/saudi-arabia/",
    flagImage: "https://flagcdn.com/w640/sa.png",
    christianPopulation: "2,200,000",
    population: "36,900,000",
    mainReligion: "Islam",
    government: "Absolute monarchy",
    leader: "King Salman bin Abdulaziz Al Saud",
    prayerPoints: [
      "Pray for secret Saudi believers to grow in faith and fellowship.",
      "Pray for expatriate Christians to witness wisely.",
      "Pray for seekers to access Scripture and faithful teaching.",
    ],
  },
  {
    rank: 14,
    name: "Myanmar",
    country: "Myanmar",
    url: "https://www.opendoors.org/en-US/persecution/countries/myanmar/",
    flagImage: "https://flagcdn.com/w640/mm.png",
    christianPopulation: "4,400,000",
    population: "54,600,000",
    mainReligion: "Buddhism",
    government: "Military junta",
    leader: "Min Aung Hlaing",
    prayerPoints: [
      "Pray for churches caught in conflict and displacement.",
      "Pray for ethnic minority believers under military pressure.",
      "Pray for courage, relief, and peace.",
    ],
  },
  {
    rank: 15,
    name: "Maldives",
    country: "Maldives",
    url: "https://www.opendoors.org/en-US/persecution/countries/maldives/",
    flagImage: "https://flagcdn.com/w640/mv.png",
    christianPopulation: "Very few",
    population: "521,000",
    mainReligion: "Islam",
    government: "Presidential republic",
    leader: "Mohamed Muizzu",
    prayerPoints: [
      "Pray for hidden believers to find safe fellowship.",
      "Pray for seekers to encounter Scripture and Christian witness.",
      "Pray for wisdom among expatriate Christians.",
    ],
  },
  {
    rank: 16,
    name: "China",
    country: "China",
    url: "https://www.opendoors.org/en-US/persecution/countries/china/",
    flagImage: "https://flagcdn.com/w640/cn.png",
    christianPopulation: "96,700,000",
    population: "1,425,700,000",
    mainReligion: "Unaffiliated / folk religion",
    government: "Communist one-party state",
    leader: "Xi Jinping",
    prayerPoints: [
      "Pray for churches navigating surveillance and pressure.",
      "Pray for pastors and families facing restrictions.",
      "Pray for faithful discipleship among young believers.",
    ],
  },
  {
    rank: 17,
    name: "Mali",
    country: "Mali",
    url: "https://www.opendoors.org/en-US/persecution/countries/mali/",
    flagImage: "https://flagcdn.com/w640/ml.png",
    christianPopulation: "500,000",
    population: "23,300,000",
    mainReligion: "Islam",
    government: "Military junta",
    leader: "Assimi Goita",
    prayerPoints: [
      "Pray for believers threatened by extremist violence.",
      "Pray for churches serving displaced families.",
      "Pray for peace and courageous witness.",
    ],
  },
  {
    rank: 18,
    name: "Iraq",
    country: "Iraq",
    url: "https://www.opendoors.org/en-US/persecution/countries/iraq/",
    flagImage: "https://flagcdn.com/w640/iq.png",
    christianPopulation: "164,000",
    population: "45,500,000",
    mainReligion: "Islam",
    government: "Federal parliamentary republic",
    leader: "Abdul Latif Rashid",
    prayerPoints: [
      "Pray for ancient Christian communities seeking stability.",
      "Pray for converts facing pressure from family and society.",
      "Pray for churches to rebuild and serve with hope.",
    ],
  },
  {
    rank: 19,
    name: "Algeria",
    country: "Algeria",
    url: "https://www.opendoors.org/en-US/persecution/countries/algeria/",
    flagImage: "https://flagcdn.com/w640/dz.png",
    christianPopulation: "144,000",
    population: "45,600,000",
    mainReligion: "Islam",
    government: "Presidential republic",
    leader: "Abdelmadjid Tebboune",
    prayerPoints: [
      "Pray for churches facing closure and legal pressure.",
      "Pray for believers from Muslim backgrounds.",
      "Pray for wisdom, unity, and perseverance.",
    ],
  },
  {
    rank: 20,
    name: "Mauritania",
    country: "Mauritania",
    url: "https://www.opendoors.org/en-US/persecution/countries/mauritania/",
    flagImage: "https://flagcdn.com/w640/mr.png",
    christianPopulation: "Very few",
    population: "4,900,000",
    mainReligion: "Islam",
    government: "Presidential republic",
    leader: "Mohamed Ould Ghazouani",
    prayerPoints: [
      "Pray for hidden believers under severe family and social pressure.",
      "Pray for access to Scripture and secure discipleship.",
      "Pray for the gospel to bring hope in isolated communities.",
    ],
  },
];

Deno.serve((req) => {
  if (req.method === "OPTIONS") return optionsResponse();
  const manilaDay = Math.floor((Date.now() + 8 * 60 * 60 * 1000) / 86400000);
  const index = (manilaDay * 17 + 11) % COUNTRIES.length;
  return json(COUNTRIES[index]);
});
